"""update models about homework and file

Revision ID: 045da421f328
Revises: 6a687f6867df
Create Date: 2021-10-28 14:18:56.699111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045da421f328'
down_revision = '6a687f6867df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False, comment='上传者用户id'),
    sa.Column('category', sa.BigInteger(), nullable=False, comment='文件类型: 1-图像 2-视频 3-音频 4-文档'),
    sa.Column('file_path', sa.String(), nullable=False, comment='文件路径'),
    sa.Column('compressed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否压缩完成'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('file_info_uploader_id_idx', 'file_info', ['uploader_id'], unique=False)
    op.create_table('file_reference',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('file_id', sa.BigInteger(), nullable=False, comment='文件id'),
    sa.Column('ref_type', sa.String(length=2), nullable=False, comment='引用类型: 1-用户反馈 2-作业 3-作业作答'),
    sa.Column('referenced_id', sa.BigInteger(), nullable=False, comment='引用对象id'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('file_reference_referenced_id_idx', 'file_reference', ['referenced_id'], unique=False)
    op.create_table('homework_answer_check',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('reviewer_member_id', sa.BigInteger(), nullable=False, comment='批改人成员id'),
    sa.Column('category', sa.String(length=2), nullable=False, comment='批改类型: 1-大图批改'),
    sa.Column('content', sa.String(), nullable=False, comment='批改内容'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('homework_answer_check_reviewer_member_id_idx', 'homework_answer_check', ['reviewer_member_id'], unique=False)
    op.create_table('homework_comment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('reviewer_member_id', sa.BigInteger(), nullable=False, comment='点评人成员id'),
    sa.Column('comment', sa.String(), nullable=False, comment='点评正文'),
    sa.Column('rejected', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='是否打回'),
    sa.Column('score', sa.String(length=2), nullable=True, comment='作业评分: A B C D E 0表示已阅'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('homework_comment_reviewer_member_id_idx', 'homework_comment', ['reviewer_member_id'], unique=False)
    op.create_table('message_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('related_id', sa.BigInteger(), nullable=True, comment='关联对象id'),
    sa.Column('content', sa.String(), nullable=True, comment='消息正文'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('message_content_related_id_idx', 'message_content', ['related_id'], unique=False)
    op.alter_column('feedback', 'category',
               existing_type=sa.VARCHAR(length=2),
               comment='反馈类型: 1-产品建议 其他-功能异常',
               existing_comment='反馈类型: 0-产品建议 其他-功能异常',
               existing_nullable=False)
    op.drop_column('feedback', 'images')
    op.drop_column('homework', 'audios')
    op.drop_column('homework', 'docs')
    op.drop_column('homework', 'images')
    op.drop_column('homework', 'videos')
    op.add_column('homework_answer', sa.Column('status_id', sa.BigInteger(), nullable=False, comment='关联的作业作答情况id'))
    op.add_column('homework_answer', sa.Column('evaluation_id', sa.BigInteger(), nullable=True, comment='关联的作业点评id'))
    op.add_column('homework_answer', sa.Column('answer_check_id', sa.BigInteger(), nullable=True, comment='关联的作业批改id'))
    op.add_column('homework_answer', sa.Column('category', sa.String(length=2), server_default='1', nullable=False, comment='作答类型: 1-作答2-重做3-订正'))
    op.add_column('homework_answer', sa.Column('desc', sa.Text(), nullable=False, comment='作答描述'))
    op.drop_column('homework_answer', 'audios')
    op.drop_column('homework_answer', 'docs')
    op.drop_column('homework_answer', 'images')
    op.drop_column('homework_answer', 'videos')
    op.add_column('homework_answer_status', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'))
    op.add_column('homework_answer_status', sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'))
    op.alter_column('homework_answer_status', 'score',
               existing_type=sa.VARCHAR(length=1),
               server_default=None,
               type_=sa.String(length=2),
               comment='作业评分: A B C D E 0表示已阅',
               existing_comment='作业评分: 1-A 2-B 3-C 4-D',
               existing_nullable=True)
    op.alter_column('homework_answer_status', 'status',
               existing_type=sa.VARCHAR(length=2),
               comment='作业状态 1-待提交 2-已提交 3-待重做 4-已批改 5-已订正 6-未反馈',
               existing_comment='作业状态',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::character varying"))
    op.drop_index('homework_answer_status_status_idx', table_name='homework_answer_status')
    op.add_column('message', sa.Column('content_id', sa.BigInteger(), nullable=False, comment='消息内容id'))
    op.drop_column('message', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True, comment='内容'))
    op.drop_column('message', 'content_id')
    op.create_index('homework_answer_status_status_idx', 'homework_answer_status', ['status'], unique=False)
    op.alter_column('homework_answer_status', 'status',
               existing_type=sa.VARCHAR(length=2),
               comment='作业状态',
               existing_comment='作业状态 1-待提交 2-已提交 3-待重做 4-已批改 5-已订正 6-未反馈',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::character varying"))
    op.alter_column('homework_answer_status', 'score',
               existing_type=sa.String(length=2),
               server_default=sa.text("'0'::character varying"),
               type_=sa.VARCHAR(length=1),
               comment='作业评分: 1-A 2-B 3-C 4-D',
               existing_comment='作业评分: A B C D E 0表示已阅',
               existing_nullable=True)
    op.drop_column('homework_answer_status', 'update_time')
    op.drop_column('homework_answer_status', 'create_time')
    op.add_column('homework_answer', sa.Column('videos', sa.VARCHAR(), autoincrement=False, nullable=True, comment='视频'))
    op.add_column('homework_answer', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True, comment='图片'))
    op.add_column('homework_answer', sa.Column('docs', sa.VARCHAR(), autoincrement=False, nullable=True, comment='文档'))
    op.add_column('homework_answer', sa.Column('audios', sa.VARCHAR(), autoincrement=False, nullable=True, comment='声音'))
    op.drop_column('homework_answer', 'desc')
    op.drop_column('homework_answer', 'category')
    op.drop_column('homework_answer', 'answer_check_id')
    op.drop_column('homework_answer', 'evaluation_id')
    op.drop_column('homework_answer', 'status_id')
    op.add_column('homework', sa.Column('videos', sa.VARCHAR(), autoincrement=False, nullable=True, comment='视频'))
    op.add_column('homework', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True, comment='图片'))
    op.add_column('homework', sa.Column('docs', sa.VARCHAR(), autoincrement=False, nullable=True, comment='文档'))
    op.add_column('homework', sa.Column('audios', sa.VARCHAR(), autoincrement=False, nullable=True, comment='声音'))
    op.add_column('feedback', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True, comment='用户反馈图片'))
    op.alter_column('feedback', 'category',
               existing_type=sa.VARCHAR(length=2),
               comment='反馈类型: 0-产品建议 其他-功能异常',
               existing_comment='反馈类型: 1-产品建议 其他-功能异常',
               existing_nullable=False)
    op.drop_index('message_content_related_id_idx', table_name='message_content')
    op.drop_table('message_content')
    op.drop_index('homework_comment_reviewer_member_id_idx', table_name='homework_comment')
    op.drop_table('homework_comment')
    op.drop_index('homework_answer_check_reviewer_member_id_idx', table_name='homework_answer_check')
    op.drop_table('homework_answer_check')
    op.drop_index('file_reference_referenced_id_idx', table_name='file_reference')
    op.drop_table('file_reference')
    op.drop_index('file_info_uploader_id_idx', table_name='file_info')
    op.drop_table('file_info')
    # ### end Alembic commands ###
