"""modify model Slideshow to EntrancePage

Revision ID: 08fafe23a25d
Revises: f08378a871be
Create Date: 2021-08-24 15:56:29.151226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08fafe23a25d'
down_revision = 'f08378a871be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrance_page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('src', sa.String(), nullable=False, comment='图片链接'),
    sa.Column('desc', sa.String(), nullable=True, comment='图片描述'),
    sa.Column('target', sa.String(), nullable=True, comment='页面路由'),
    sa.Column('type', sa.String(length=2), nullable=False, comment='图片类型: 1-启动页图片 2-引导页图片'),
    sa.Column('status', sa.String(length=2), server_default='1', nullable=False, comment='状态: 0-停用 1-启用'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('slideshow')
    # ### end Alembic commands ###

    from app.alembic.insert_seed_data import insert_entrance_pages
    insert_entrance_pages(op)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slideshow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('src', sa.VARCHAR(), autoincrement=False, nullable=False, comment='图片链接'),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True, comment='图片描述'),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True, comment='页面路由'),
    sa.Column('herf', sa.VARCHAR(), autoincrement=False, nullable=True, comment='跳转外链'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='名字'),
    sa.Column('status', sa.VARCHAR(length=2), server_default=sa.text("'1'::character varying"), autoincrement=False, nullable=False, comment='状态: 0-停用 1-启用'),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id', name='slideshow_pkey')
    )
    op.drop_table('entrance_page')
    # ### end Alembic commands ###
