"""init db

Revision ID: 10a208fb3dac
Revises: 
Create Date: 2021-08-17 08:48:05.796584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a208fb3dac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply4class',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='申请人id'),
    sa.Column('name', sa.String(), nullable=False, comment='申请姓名'),
    sa.Column('auditor', sa.String(), nullable=True, comment='审核人姓名'),
    sa.Column('auditor_member_id', sa.BigInteger(), nullable=True, comment='审核人的班级成员id'),
    sa.Column('class_id', sa.BigInteger(), nullable=False, comment='申请加入班级的id'),
    sa.Column('family_relation', sa.String(length=2), nullable=True, comment='亲属关系id: 1-本人 2-爸爸 3-妈妈 4-爷爷 5-奶奶 6-外公 7-外婆 8-哥哥 9-姐姐'),
    sa.Column('subject_id', sa.Integer(), nullable=True, comment='任教科目id'),
    sa.Column('telephone', sa.String(length=11), nullable=True, comment='电话号码'),
    sa.Column('result', sa.String(length=2), server_default='1', nullable=False, comment='审核结果: 0-驳回 1-审核中 2-通过'),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True, comment='结束时间'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('apply4class_class_id_idx', 'apply4class', ['class_id'], unique=False)
    op.create_index('apply4class_user_id_idx', 'apply4class', ['user_id'], unique=False)
    op.create_table('class',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='班级id，主键'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='所属学校id'),
    sa.Column('grade', sa.Integer(), nullable=True, comment='年级'),
    sa.Column('class', sa.Integer(), nullable=True, comment='班级'),
    sa.Column('need_audit', sa.Boolean(), server_default=sa.text('True'), nullable=False, comment='加入班级是否需要审核'),
    sa.Column('contact', sa.String(length=11), nullable=False, comment='联系方式'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'grade', 'class')
    )
    op.create_index('class_school_id_idx', 'class', ['school_id'], unique=False)
    op.create_table('class_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('class_id', sa.BigInteger(), nullable=False, comment='班级id'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户id'),
    sa.Column('name', sa.String(), nullable=False, comment='教师/学生姓名'),
    sa.Column('member_role', sa.String(length=2), nullable=False, comment='成员身份: 1-班主任 2-任课老师 3-学生'),
    sa.Column('subject_id', sa.Integer(), nullable=True, comment='任教科目id'),
    sa.Column('family_relation', sa.String(length=2), nullable=True, comment='亲属关系id: 1-本人 2-爸爸 3-妈妈 4-爷爷 5-奶奶 6-外公 7-外婆 8-哥哥 9-姐姐'),
    sa.Column('telephone', sa.String(length=11), nullable=False, comment='电话号码'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('class_member_class_id_idx', 'class_member', ['class_id'], unique=False)
    op.create_index('class_member_name_idx', 'class_member', ['name'], unique=False)
    op.create_index('class_member_user_id_idx', 'class_member', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户id'),
    sa.Column('category', sa.Integer(), nullable=False, comment='反馈类型'),
    sa.Column('desc', sa.Text(), nullable=False, comment='反馈内容描述'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('feedback_user_id_idx', 'feedback', ['user_id'], unique=False)
    op.create_table('feedback_image',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('feedback_id', sa.BigInteger(), nullable=False, comment='用户反馈id'),
    sa.Column('order', sa.Integer(), nullable=False, comment='顺序'),
    sa.Column('base64', sa.Text(), nullable=False, comment='图片base64数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('feedback_image_feedback_id_idx', 'feedback_image', ['feedback_id'], unique=False)
    op.create_table('homepage_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('target', sa.String(), nullable=False, comment='资源路径'),
    sa.Column('title', sa.String(), nullable=False, comment='标题'),
    sa.Column('icon', sa.String(), nullable=False, comment='图标URL'),
    sa.Column('status', sa.String(length=2), server_default='1', nullable=False, comment='状态: 0-停用 1-启用'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('code', sa.Integer(), nullable=False, comment='行政区编号，主键'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='地区名称'),
    sa.Column('parent_code', sa.Integer(), nullable=True, comment='父级地区id'),
    sa.Column('level', sa.Integer(), nullable=False, comment='地区级别: 1-省、自治区、直辖市 2-地级市、地区、自治州、盟 3-市辖区、县级市、县'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('school',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='学校id，主键'),
    sa.Column('name', sa.String(), nullable=False, comment='学校名称'),
    sa.Column('region_code', sa.Integer(), nullable=False, comment='所在地区的地区码'),
    sa.Column('address', sa.String(), nullable=True, comment='学校地址'),
    sa.Column('study_stage', sa.String(), nullable=True, comment='学段，多个值以","分隔: 1-小学 2-初中 3-高中'),
    sa.Column('school_id', sa.BigInteger(), nullable=True, comment='云平台 - 学校id'),
    sa.Column('parent_org_id', sa.BigInteger(), nullable=True, comment='云平台 - 上级机构id'),
    sa.Column('curr_cpscode', sa.Integer(), nullable=True, comment='全品学码'),
    sa.Column('data_source', sa.String(length=2), nullable=False, comment='数据来源: 1-api网关同步 2-小学数字教辅中心创建'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('slideshow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('src', sa.String(), nullable=False, comment='图片链接'),
    sa.Column('desc', sa.String(), nullable=True, comment='图片描述'),
    sa.Column('target', sa.String(), nullable=True, comment='页面路由'),
    sa.Column('herf', sa.String(), nullable=True, comment='跳转外链'),
    sa.Column('name', sa.String(), nullable=True, comment='名字'),
    sa.Column('status', sa.String(length=2), server_default='1', nullable=False, comment='状态: 0-停用 1-启用'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='学科id，主键'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='学科名'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sys_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id，主键'),
    sa.Column('key', sa.String(), nullable=False, comment='配置项KEY'),
    sa.Column('value', sa.String(), nullable=False, comment='配置项VALUE'),
    sa.Column('desc', sa.String(), nullable=True, comment='配置项说明'),
    sa.Column('type', sa.Integer(), nullable=False, comment='配置类型'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户id，主键'),
    sa.Column('wx_name', sa.String(), nullable=True, comment='微信名称'),
    sa.Column('avatar', sa.String(), nullable=True, comment='头像URL'),
    sa.Column('openid', sa.String(), nullable=False, comment='用户openid'),
    sa.Column('telephone', sa.String(length=11), nullable=True, comment='电话号码'),
    sa.Column('current_member_id', sa.BigInteger(), nullable=True, comment='当前班级成员id'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=False, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_index('user_openid_idx', 'user', ['openid'], unique=False)
    op.create_index('user_wx_name_idx', 'user', ['wx_name'], unique=False)
    # ### end Alembic commands ###

    # 初始化数据库时插入种子数据
    from app.alembic.insert_seed_data import insert_seed_data
    insert_seed_data(op)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_wx_name_idx', table_name='user')
    op.drop_index('user_openid_idx', table_name='user')
    op.drop_table('user')
    op.drop_table('sys_config')
    op.drop_table('subject')
    op.drop_table('slideshow')
    op.drop_table('school')
    op.drop_table('region')
    op.drop_table('homepage_menu')
    op.drop_index('feedback_image_feedback_id_idx', table_name='feedback_image')
    op.drop_table('feedback_image')
    op.drop_index('feedback_user_id_idx', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('class_member_user_id_idx', table_name='class_member')
    op.drop_index('class_member_name_idx', table_name='class_member')
    op.drop_index('class_member_class_id_idx', table_name='class_member')
    op.drop_table('class_member')
    op.drop_index('class_school_id_idx', table_name='class')
    op.drop_table('class')
    op.drop_index('apply4class_user_id_idx', table_name='apply4class')
    op.drop_index('apply4class_class_id_idx', table_name='apply4class')
    op.drop_table('apply4class')
    # ### end Alembic commands ###
