"""update feedback model

Revision ID: 66d946087868
Revises: 08fafe23a25d
Create Date: 2021-08-30 16:31:04.635082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66d946087868'
down_revision = '08fafe23a25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('feedback_image_feedback_id_idx', table_name='feedback_image')
    op.drop_table('feedback_image')
    op.add_column('feedback', sa.Column('images', sa.String(), nullable=True, comment='用户反馈图片'))
    op.alter_column('feedback', 'category',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               comment='反馈类型: 0-产品建议 其他-功能异常',
               existing_comment='反馈类型',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'category',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               comment='反馈类型',
               existing_comment='反馈类型: 0-产品建议 其他-功能异常',
               existing_nullable=False)
    op.drop_column('feedback', 'images')
    op.create_table('feedback_image',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('feedback_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='用户反馈id'),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False, comment='顺序'),
    sa.Column('base64', sa.TEXT(), autoincrement=False, nullable=False, comment='图片base64数据'),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name='feedback_image_pkey')
    )
    op.create_index('feedback_image_feedback_id_idx', 'feedback_image', ['feedback_id'], unique=False)
    # ### end Alembic commands ###
