"""add model Group and GroupMember

Revision ID: e090aa701634
Revises: 66d946087868
Create Date: 2021-09-09 16:48:57.952321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e090aa701634'
down_revision = '66d946087868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_group_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属小组id'),
    sa.Column('member_id', sa.BigInteger(), nullable=False, comment='成员id'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'member_id')
    )
    op.create_index('class_group_member_group_id_idx', 'class_group_member', ['group_id'], unique=False)
    op.create_index('class_group_member_member_id_idx', 'class_group_member', ['member_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=10), nullable=False, comment='小组名称'),
    sa.Column('class_id', sa.BigInteger(), nullable=False, comment='所属班级id'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'class_id')
    )
    op.create_index('group_class_id_idx', 'group', ['class_id'], unique=False)
    op.alter_column('apply4class', 'family_relation',
               existing_type=sa.VARCHAR(length=2),
               comment='亲属关系: 1-本人 2-爸爸 3-妈妈 4-爷爷 5-奶奶 6-外公 7-外婆 8-哥哥 9-姐姐',
               existing_comment='亲属关系id: 1-本人 2-爸爸 3-妈妈 4-爷爷 5-奶奶 6-外公 7-外婆 8-哥哥 9-姐姐',
               existing_nullable=True)
    op.drop_column('apply4class', 'auditor')
    op.alter_column('class_member', 'name',
               existing_type=sa.VARCHAR(),
               comment='成员姓名',
               existing_comment='教师/学生姓名',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_member', 'name',
               existing_type=sa.VARCHAR(),
               comment='教师/学生姓名',
               existing_comment='成员姓名',
               existing_nullable=False)
    op.add_column('apply4class', sa.Column('auditor', sa.VARCHAR(), autoincrement=False, nullable=True, comment='审核人姓名'))
    op.alter_column('apply4class', 'family_relation',
               existing_type=sa.VARCHAR(length=2),
               comment='亲属关系id: 1-本人 2-爸爸 3-妈妈 4-爷爷 5-奶奶 6-外公 7-外婆 8-哥哥 9-姐姐',
               existing_comment='亲属关系: 1-本人 2-爸爸 3-妈妈 4-爷爷 5-奶奶 6-外公 7-外婆 8-哥哥 9-姐姐',
               existing_nullable=True)
    op.drop_index('group_class_id_idx', table_name='group')
    op.drop_table('group')
    op.drop_index('class_group_member_member_id_idx', table_name='class_group_member')
    op.drop_index('class_group_member_group_id_idx', table_name='class_group_member')
    op.drop_table('class_group_member')
    # ### end Alembic commands ###
